### ISSUE TITLE
API error when applying terraform with not set sslCertificates.alertThreshold

### ISSUE THREAD

**Issue by tkowalcz** [bitfield/terraform-provider-checkly#10]
**Terraform version:** 0.12.24
**Provider version:** 0.4.0
**The problem:** Applying plan that seems correct (no errors or warnings) fails with API error.

**Steps to reproduce:**
run `terraform apply` on file sam as in #8.

**Result:**
(manually formatted for clarity)

```json
Error: API error: unexpected response status 400: 

{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"AlertSettingsSchema\" fails because [child \"sslCertificates\" fails because [child \"alertThreshold\" fails because [\"alertThreshold\" must be one of [3, 7, 14, 30]]]]",
  "validation": {
    "source": "payload",
    "keys": [
      "alertSettings.sslCertificates.alertThreshold"
    ]
  }
}
```

**Comment by bitfield** [comment]
Thanks @tkowalcz! At the moment, the Terraform provider does a limited amount of validation on input, but evidently not this. I'll add that check for you and let you know once an updated version is released. Please open issues for any other missing validation you find!

**Comment by tnolet** [comment]
@tkowalcz I think the right way to go here is that we provide sane defaults on the REST API side. This property `alertSettings.sslCertificates.alertThreshold` is documented in the API docs, but it is nested and therefore easily forgotten. It is also does not really need a "hard" user decision on initial creation. A sane default is fine and we can just use the same settings as the UI.

**Comment by tkowalcz** [comment]
For me the biggest issue (which is pretty small, really :)) is that the plan is fine by provider standards but fails to apply.

**Comment by tnolet** [comment]
@tkowalcz @bitfield just validated that the Checkly API is already providing a full default for all alert setting when not providing it in the JSON body on POST. 

The defaults are:

```json
  "alertSettings": {
    "escalationType": "RUN_BASED",
    "runBasedEscalation": {
      "failedRunThreshold": 1
    },
    "timeBasedEscalation": {
      "minutesFailingThreshold": 5
    },
    "reminders": {
      "amount": 0,
      "interval": 5
    },
    "sslCertificates": {
      "enabled": true,
      "alertThreshold": 30
    }
  }
```
AFAICS this issue is related to https://github.com/bitfield/terraform-provider-checkly/issues/8

**Comment by bitfield** [comment]
This should now be fixed following the recent API updates.
