### ISSUE TITLE
Provider shows no version on `terraform version`

### ISSUE THREAD

**Issue by tnolet** [bitfield/terraform-provider-checkly#11]
After installing, there is no version displayed. This makes debugging harder.
```
$ terraform version
Terraform v0.12.24
+ provider.checkly (unversioned)
```

**Comment by bitfield** [comment]
Fixed in `v0.5.2` by creating the release artifacts with the version tag as part of the binary name, and updating the install script to take account of this:

```
terraform version   
Terraform v0.12.24
+ provider.checkly v0.5.2
```
