### ISSUE TITLE
Diff on basic_auth even when not using it

### ISSUE THREAD

**Issue by SaaldjorMike** [bitfield/terraform-provider-checkly#14]
As part of https://github.com/bitfield/terraform-provider-checkly/issues/8 I mentioned I hoped to work around the "diff-even-without-changes" problem by just explicitly stating everything so it would stop show the properties as being removed in the diff.

Specifying all the alert settings seemed to work out somewhat ok, but then I wanted to do the same with the diff's shown in the request where we also had no desired changes even if the plugin showed changes.

It showed something like this (I don't have the exact output but hope this will do for now):

```
      + request {
          + body_type        = "NONE"
          + follow_redirects = true
          + method           = "GET"
          + url              = "https://some-website"

          + assertion {
              + comparison = "NOT COTAINS"
              + source     = "TEXT_BODY"
              + target     = "some string I do not want to see"
            }
        }

      - request {
          - body_type        = "NONE" -> null
          - follow_redirects = true -> null
          - headers          = {} -> null
          - method           = "GET" -> null
          - query_parameters = {} -> null
          - url              = "https://some-website" -> null

          - assertion {
              - comparison = "NOT COTAINS" -> null
              - source     = "TEXT_BODY" -> null
              - target     = "some string I do not want to see" -> null
            }

          - basic_auth {}
        }

```

Notice that the `request` block it wants to add is without `headers`, `query_parameters` and `basic_auth` (which is what I want), so I hoped I could just set them explicitly to be "empty"/"unset". This seems like it would work for `headers` and `query_parameters`, but it does not work for `basic_auth` because the provider requires you to define a `username` and `password` property on the `basic_auth` block, but in my case I don't even want to use `basic_auth`.

**Comment by bitfield** [comment]
Thanks, @SaaldjorMike. I'm pretty sure this is due to the same underlying issue that's causing #8, so I'll close this for now, with your permission. When I've fixed #8 this should also be fixed, and if not I'll reopen it.
