### ISSUE TITLE
Manually deleting check breaks terraform

### ISSUE THREAD

**Issue by tkowalcz** [bitfield/terraform-provider-checkly#9]
**Terraform version:** 0.12.24
**Provider version:** 0.4.0
**The problem:** Manually deleting terraform managed check breaks terraform.

**Steps to reproduce:**
1. Create check via terraform
2. Delete check via UI
3. run `terraform apply` or `terraform plan`

**Result:**

```
checkly_check.example-check: Refreshing state... [id=36152cfc-f65c-42a9-b922-7eadd23c5840]

Error: API error: unexpected response status 404: "{\"statusCode\":404,\"error\":\"Not Found\"}"
```

**Comment by tkowalcz** [comment]
I need to add to `alert_settings`:

```
    ssl_certificates {
      enabled = false
    }
```

**Comment by bitfield** [comment]
Hi @tkowalcz! Thanks for the issue report.

I've seen this problem too. I'll have a look into the cause and get some information for you once I have it.

**Comment by bitfield** [comment]
Migrated to https://github.com/checkly/terraform-provider-checkly/issues/11
